---@meta
---@class pickSessionAnimatorState
---@field mesh niNode
---@field helper niNode
---@field item tes3itemStack
---@field originalHelperRotation tes3matrix33
---@field currentHelperAngle number
---@field targetHelperAngle number
---@field blocked boolean
---@field jigglePhase number
---@field jiggleOffset number
