---@meta
---@class pickSessionAnimatorState
---@field mesh niNode
---@field helper niNode
---@field item tes3itemStack
---@field originalHelperRotation tes3matrix33
---@field originalPickRotation tes3matrix33|nil
---@field currentHelperAngle number
---@field targetHelperAngle number
---@field blocked boolean
---@field jiggling boolean
---@field jigglePhase number
---@field jiggleOffset number
