---@meta
---@class initializedService : service
---@field public initialize fun(services:serviceCollection):boolean,string|nil
---@field public uninitialize? fun()
---@field public initalized? boolean
---@field public dependencies? fun(services:serviceCollection):initializedService[]
