---@meta
---@class lockpickingSession
---@field public activator tes3reference
---@field public picks tes3itemStack[]
---@field public eligiblePicks { [string]: boolean }
---@field public lock lock
---@field public knife knife
---@field public pick pick?
---@field public sweetSpotCenter number
---@field public sweetSpot { center: number, radius: number, gradientWidth: number }|nil
---@field public paused boolean
