---@meta
---@class lockpickingEndEventData
---@field public lock lock
---@field public knife knife
---@field public pick pick
---@field public activator tes3containerInstance|tes3door
---@field public success boolean
