---@meta
---@class timerManager.start.params
---@field public durationInSeconds number
---@field public callback fun(callback:mwseTimerCallbackData)?
---@field public finishedCallback fun(configuration:timerData)?
---@field public cancelOn string[]?
---@field public data? timerData
