---@meta
---@class timerManager.start.params
---@field public durationInSeconds number
---@field public callback fun(data: timerData?)?
---@field public cancelOn string[]?
---@field public pauseOn string[]?
---@field public resumeOn string[]?
---@field public data? timerData
