---@meta
---@class lock
---@field public mesh niNode
---@field public cylinder cylinder
---@field public blocked boolean
---@field public rotatingClockwise boolean
---@field public rotatingCounterclockwise boolean
---@field public container tes3containerInstance
