---@meta
---@class onMeshAnimatorTimerData : timerData
---@field public node niNode
---@field public keyframes nodeAnimatorKeyframe[]
---@field public currentPhase number
---@field public currentFrame integer
